name: Nightly Test run (Jahia SN)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests:
    uses:  Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee-dev:8-SNAPSHOT
      module_id: jahia-multi-factor-authentication
      testrail_project: Jahia Multi-Factor Authentication Module
      pagerduty_incident_service: jahia-multi-factor-authentication-JahiaSN
      provisioning_manifest: provisioning-manifest-snapshot.yml
      artifact_prefix: jahia-multi-factor-authentication-nightly-sn
      module_branch: ${{ github.ref }}
