# TODO to be renamed as "On Pull Request"
name: On Code Change (PR)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-reusable-workflow:
    uses: Jahia/jahia-modules-action/.github/workflows/jahia-modules_on-pull-request.yml@guild-day-simplify-reusable-workflows
    secrets: inherit
